---
# Include variables and define needed variables.
- name: Include OS-specific variables.
  include_vars: "{{ item }}"
  with_first_found:
    - ../vars/{{ ansible_os_family }}.yml

# Include play to install Plex Media Server
- include: "{{ ansible_os_family }}/install.yml"

# This task is after the install task meaning
# the package ought to create them and not ansible
- name: Verify/Manage Plex Media Server group
  group:
    name: "{{ plex_media_server_group }}"
    state: present

- name: Verify Plex Media Server user
  user:
    name: "{{ plex_media_server_user }}"
    groups: "{{ plex_media_server_group }}"
    state: present

- name: Ensure Plex Media Server has selected state and enabled on boot.
  service:
    name: "{{ plex_media_server_service }}"
    state: "{{ plex_media_server_state }}"
    enabled: "{{ plex_media_server_enabled }}"
  when: (plex_media_server_manage_service)

- meta: flush_handlers
