---
# Include Plex Media Server APT Repository
- include: "repo.yml"

- name: Install Plex Media Server
  apt:
    deb: "https://downloads.plex.tv/plex-media-server/{{ plex_media_server_version }}/plexmediaserver_{{ plex_media_server_version }}_amd64.deb"
    state: present
  notify: 'Restart Plex Media Server'
  become: yes
